# Generated by Django 5.2.5 on 2025-12-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_quantity_alter_cartitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
