# Generated by Django 5.2.5 on 2025-10-18 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Anonymous session identifier', max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Optional: track visitor IP', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser or device info', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Views',
                'db_table': 'product_views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='product_vie_product_4161dd_idx')],
            },
        ),
    ]
